version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MODE: primary
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PRIMARY_PORT: 5432
