server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 100
      minimum-idle: 10
      connection-test-query: SELECT 1
  flyway:
    user: postgres
    password: postgres
    locations: classpath:/db/migration,classpath:demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
